import type { Metadata } from "next";
import { Jura, Antic_Slab, Kode_Mono } from "next/font/google";
import "./globals.css";

const fontSans = Jura({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontSerif = Antic_Slab({
  variable: "--font-serif",
  weight: "400",
  subsets: ["latin"],
});

const fontMono = Kode_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} min-h-screen antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
